title: Paul Schaefer
tagline: web designer and developer
email: yeppaul2@gmail.com
description: Paul Schaefer is a web designer and developer living in the lovely Pittsburgh, PA.
baseurl: ""
url: "https://pschfr.github.io"
permalink: /:categories/:title/
includes:
- favicons
- images
- pages
sass:
    style: compressed
