# Welcome to Jekyll!
# https://github.com/pschfr/pschfr.github.io
title: Paul Schaefer
tagline: web designer and developer
email: yeppaul2@gmail.com
description: Paul Schaefer is a web designer and developer living in the lovely Pittsburgh, PA.
baseurl: ""
url: "https://paulmakesthe.net"
permalink: /:categories/:title/ # e.g. articles/title.html

# Adds other folders besides _includes, _layouts, _posts
includes:
- favicons
- pages
- js

# Removes files and folders from jekyll build
exclude:
- node_modules
- gulpfile.js
- gulpfile_example.js
- README.md
- svg

# Obviously compresses the Sass output.
sass:
    style: compressed

# The HTML is compressed via _layouts/compress.html
# http://jch.penibelst.de/
