# Welcome to Jekyll!

# SITE VARIABLES
title: Paul Schaefer
tagline: web designer & developer
email: yeppaul2@gmail.com
description: Paul Schaefer is a web designer and developer living in the lovely Pittsburgh, PA.

# BUILD SETTINGS
baseurl: ""                     # the subpath of your site, e.g. "/blog" or ""
url: "https://pschfr.github.io" # the base hostname & protocol for your (live) site
incremental: true               # enables the experimental feature that only re-builds edited posts
permalink: /:title/             # assists with page URLs, displays as /contact/

# REQUIRED FILES
includes:
- favicons
- images
- css
- js
- pages

# for use when building the contact page later
# http://mattgemmell.com/page-specific-assets-with-jekyll/
# http://www.tonysheng.com/howto/conditional-cta-jekyll/
