# Welcome to Jekyll!
# Site settings
title: Paul Schaefer
tagline: web designer & developer
email: yeppaul2@gmail.com
description: Paul Schaefer is a designer and web developer living in the lovely Pittsburgh, PA

baseurl: ""                     # the subpath of your site, e.g. "/blog" or ""
url: "https://pschfr.github.io" # the base hostname & protocol for your (live) site

includes:
- css
- js
- favicons
- pages

# Assists with pages
permalink: /:title/

# for use when building the contact page
# http://mattgemmell.com/page-specific-assets-with-jekyll/
# http://www.tonysheng.com/howto/conditional-cta-jekyll/

# Build-specific settings
markdown: kramdown
