# Welcome to Jekyll!
# Site settings
title: Paul Schaefer
tagline: web designer & developer
email: yeppaul2@gmail.com
description: Paul Schaefer is a designer and web developer living in the lovely Pittsburgh, PA

baseurl: ""                     # the subpath of your site, e.g. /blog
url: "https://pschfr.github.io" # the base hostname & protocol for your site

includes:
- css
- js
- favicons
- pages

navigation:
- text: Home
  url: /
- text: Contact
  url: /contact/

permalink: /:title/

# for when building the contact page
# http://mattgemmell.com/page-specific-assets-with-jekyll/
# http://www.tonysheng.com/howto/conditional-cta-jekyll/

# Build settings
markdown: kramdown
